// <auto-generated />
using System;
using Jogos.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Jogos.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260913234217_JogoPlataformaRefatoracao")]
    partial class JogoPlataformaRefatoracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaEntityJogoEntity", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("JogosId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CategoriasId", "JogosId");

                    b.HasIndex("JogosId");

                    b.ToTable("CategoriaEntityJogoEntity");
                });

            modelBuilder.Entity("JogoEntityPlataformaEntity", b =>
                {
                    b.Property<int>("JogosId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PlataformasId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("JogosId", "PlataformasId");

                    b.HasIndex("PlataformasId");

                    b.ToTable("JogoEntityPlataformaEntity");
                });

            modelBuilder.Entity("Jogos.API.Domain.Entities.CategoriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "IDX_categoria_nome")
                        .IsUnique();

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("Jogos.API.Domain.Entities.DesenvolvedoraEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "IDX_desenvolvedora_nome")
                        .IsUnique();

                    b.ToTable("tb_desenvolvedora");
                });

            modelBuilder.Entity("Jogos.API.Domain.Entities.JogoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("c_data_lancamento");

                    b.Property<int>("DesenvolvedoraId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("c_desenvolvedora_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_nome");

                    b.Property<double>("Preco")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("c_preco");

                    b.HasKey("Id");

                    b.HasIndex("DesenvolvedoraId");

                    b.HasIndex(new[] { "Nome" }, "IDX_jogo_nome")
                        .IsUnique();

                    b.ToTable("tb_jogo");
                });

            modelBuilder.Entity("Jogos.API.Domain.Entities.PlataformaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_nome");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "IDX_plataforma_nome")
                        .IsUnique();

                    b.ToTable("tb_plataforma");
                });

            modelBuilder.Entity("CategoriaEntityJogoEntity", b =>
                {
                    b.HasOne("Jogos.API.Domain.Entities.CategoriaEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jogos.API.Domain.Entities.JogoEntity", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JogoEntityPlataformaEntity", b =>
                {
                    b.HasOne("Jogos.API.Domain.Entities.JogoEntity", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jogos.API.Domain.Entities.PlataformaEntity", null)
                        .WithMany()
                        .HasForeignKey("PlataformasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jogos.API.Domain.Entities.JogoEntity", b =>
                {
                    b.HasOne("Jogos.API.Domain.Entities.DesenvolvedoraEntity", "Desenvolvedora")
                        .WithMany("Jogos")
                        .HasForeignKey("DesenvolvedoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desenvolvedora");
                });

            modelBuilder.Entity("Jogos.API.Domain.Entities.DesenvolvedoraEntity", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
